export const AdminActionTypes = {

    LOGIN_REQ : "LOGIN_REQ",
    LOGIN_REQ_SUCCESS : "LOGIN_REQ_SUCCESS",
    LOGIN_REQ_FAILED : "LOGIN_REQ_FAILED",

    LOGOUT_REQ : 'LOGOUT_REQ',

    GET_USERS_REQ : 'GET_USERS_REQ',
    GET_USERS_SUCCESS : "GET_USERS_SUCCESS",
    GET_USERS_FAILED : "GET_USERS_FAILED",

    ADD_BIKE_REQ : "ADD_BIKE_REQ",
    ADD_BIKE_SUCCESS : "ADD_BIKE_SUCCESS",
    ADD_BIKE_FAILED : "ADD_BIKE_FAILED",

    GET_BIKES_REQ : "GET_BIKES_REQ",
    GET_BIKES_SUCCESS : "GET_BIKES_SUCCESS",
    GET_BIKES_FAILED : "GET_BIKES_FAILED",
    

    GET_SINGLE_BIKE_SUCCESS : "GET_SINGLE_BIKE_SUCCESS",

    GET_BIKE_VIEW : "GET_BIKE_VIEW ",
    GET_BIKE_VIEW_SUCCESS : "GET_BIKE_VIEW_SUCCESS ",
    GET_BIKE_VIEW_FAILED : "GET_BIKE_VIEW_FAILED ",

    GET_RENT_REQUESTS : "GET_RENT_REQUESTS",
    GET_RENT_REQUESTS_SUCCESS : "GET_RENT_REQUESTS_SUCCESS",
    GET_RENT_REQUESTS_FAILED : "GET_RENT_REQUESTS_FAILED",
    

    ACCEPT_RENT_REQUESTS : "ACCEPT_RENT_REQUESTS",
    ACCEPT_RENT_REQUESTS_SUCCESS : "ACCEPT_RENT_REQUESTS_SUCCESS",
    ACCEPT_RENT_REQUESTS_FAILED : 'ACCEPT_RENT_REQUESTS_FAILED',

    REJECT_RENT_REQUESTS : "REJECT_RENT_REQUESTS",
    REJECT_RENT_REQUESTS_SUCCESS :  "REJECT_RENT_REQUESTS_SUCCESS ",
    REJECT_RENT_REQUESTS_FAILED : "REJECT_RENT_REQUESTS_FAILED",
    

    DELETE_BIKE_REQ : "DELETE_BIKE_REQ",
    DELETE_BIKE_SUCCESS : "DELETE_BIKE_SUCCESS",
    DELETE_BIKE_FAILED : "DELETE_BIKE_FAILED",


    GET_LOCATION_REQ : "ADD_LOCATION_REQ",
    GET_LOCATION_SUCCESS : "ADD_LOCATION_SUCCESS",
    GET_LOCATION_FAILED : "ADD_LOCATION_FAILED",

    ADD_LOCATION_REQ : "ADD_LOCATION_REQ",
    ADD_LOCATION_SUCCESS : "ADD_LOCATION_SUCCESS",
    ADD_LOCATION_FAILED : "ADD_LOCATION_FAILED",

    DELETE_LOC_REQ : "DELETE_LOC_REQ",
    DELETE_LOC_SUCCESS : "DELETE_LOC_SUCCESS",
    DELETE_LOC_FAILED : "DELETE_LOC_FAILED",

    EDIT_LOC_REQ : "EDIT_LOC_REQ",
    EDIT_LOC_SUCCESS : "EDIT_LOC_SUCCESS",
    EDIT_LOC_FAILED : "EDIT_LOC_FAILED",

    BIKE_SEARCH_REQ : 'BIKE_SEARCH_REQ',
    BIKE_SEARCH_SUCCESS : "BIKE_SEARCH_SUCCESS",
    BIKE_SEARCH_FAILED : "BIKE_SEARCH_FAILED",

    GET_COUPONS_REQ : "GET_COUPONS_REQ",
    GET_COUPONS_SUCCESS : "GET_COUPONS_SUCCESS",
    GET_COUPONS_FAILED : "GET_COUPONS_FAILED",

    ADD_COUPON_REQ : "ADD_COUPON_REQ",
    ADD_COUPON_SUCCESS : "ADD_COUPON_SUCCESS",
    ADD_COUPON_FAILED : "ADD_COUPON_FAILED",

    EDIT_COUPON_SUCCESS : "EDIT_COUPON_SUCCESS",
    EDIT_COUPON_FAILED : "EDIT_COUPON_FAILED",

    DELETE_COUPON_SUCCESS : "DELETE_COUPON_SUCCESS",
    DELETE_COUPON_FAILED : "DELETE_COUPON_FAILED",

    GET_BOOKED_DETAILS_REQ : "GET_BOOKED_DETAILS_REQ",
    GET_BOOKED_DETAILS_SUCCESS : "GET_BOOKED_DETAILS_SUCCESS",
    GET_BOOKED_DETAILS_FAILED : "GET_BOOKED_DETAILS_FAILED",

    GET_DASHBOARD_DETAILS_REQ : "GET_DASHBOARD_DETAILS_REQ",
    GET_DASHBOARD_DETAILS_SUCCESS : "GET_DASHBOARD_DETAILS_SUCCESS",
    GET_DASHBOARD_DETAILS_FAILED : "GET_DASHBOARD_DETAILS_FAILED",

    GET_SALES_REPORT_REQ : "GET_SALES_REPORT_REQ",
    GET_SALES_REPORT_SUCCESS : "GET_SALES_REPORT_SUCCESS",
    GET_SALES_REPORT_FAILED : "GET_SALES_REPORT_FAILED",

    



    

    

    


    
    
    
    





    

}